# Generated by Django 2.2.5 on 2019-10-05 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 17, 35, 0, 448228, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
