# Generated by Django 2.2.5 on 2019-11-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='modleNumber',
            new_name='modelNumber',
        ),
    ]
