# Generated by Django 2.2.5 on 2019-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20191110_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='date',
            field=models.CharField(default=21, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='dateSold',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='purchaser',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='sellingPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appliance',
            name='ticketNum',
            field=models.IntegerField(default=0),
        ),
    ]
