# Generated by Django 2.2.5 on 2019-12-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_appliance_scraped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='scraped',
            new_name='scrapped',
        ),
    ]
